<!--Creator: Eli Hughes
    File: header.inc
    Purpose: .inc file containing html code to be used for the header section of
             index.html, contact.html, products.html, and info.html, admin.html, 
             delete.html, login.html, order.html, thanks.html, update.html
-->

<!--Company logo, name, address, operating hours-->
<div id='header'>
    <!--Company logo-->
    <a href='index.html'><img id='logo' src='logo.png' alt='Tony the Peanut Man logo'></a>  
    <h1 id='companyName'>Tony the Peanut Man</h1>
    <i>332 E. America St., Charleston, SC 29401</i>
    <br>
    Closed Sat/Sun, Open 10:00AM - 5:00PM the rest of the week
</div>