<!--Creator: Eli Hughes
    File: menu.inc
    Purpose: .inc file containing html code to be used for the menu section of
             index.html, contact.html, products.html, and info.html, admin.html, 
             delete.html, login.html, order.html, thanks.html, update.html.
-->

<!--Links to index.html, contact.html, and products.html-->
<div id='menu'>
    <a href='index.html'><button class='menuBtn'>Home</button></a> |
    <a href='contact.html'><button class='menuBtn'>Contact</button></a> |
    <a href='products.html'><button class='menuBtn'>Products</button></a> | 
    <a href='order.html'><img id='cartIcon' src='cart.png' alt='A shopping cart icon'></a>
</div>